### ISSUE TITLE
Checkbox value always "No" in Collected Information menu

### ISSUE THREAD

**Issue by lucagentile** [netgen/NetgenInformationCollectionBundle#16]
Hello.
It seems like that from Setup -> Collected Information -> Collections menu, the checkbox value type is taken from the "data_int" column and not "data_text". 

![image](https://user-images.githubusercontent.com/4802220/29623796-d19e2766-8827-11e7-91e0-1be44f981460.png)
![schermata 2017-08-23 alle 17 54 43](https://user-images.githubusercontent.com/4802220/29625505-323a15ea-882c-11e7-9cd6-a367f6a7d89d.png)

In fact, if I try to set data_int to 1 and even leaving the data_text empty, backend page shows "Yes".
![image](https://user-images.githubusercontent.com/4802220/29625360-be7d6134-882b-11e7-9e7c-b57b37627a73.png)
![image](https://user-images.githubusercontent.com/4802220/29625444-fa94ecd2-882b-11e7-9300-04b3baab2a4b.png)

**Comment by MarioBlazek** [comment]
Thanks for reporting the issue, I will resolve it asap.

**Comment by MarioBlazek** [comment]
Sorry for delay, please upgrade to v1.1.0 version of bundle it resolves your issue https://github.com/netgen/NetgenInformationCollectionBundle/releases/tag/v1.1.0 .

**Comment by lucagentile** [comment]
Problem solved, thanks!
