### ISSUE TITLE
Can't edit multilingual content in backend.

### ISSUE THREAD

**Issue by punknroll** [netgen/NetgenInformationCollectionBundle#17]
Hi, I have 3 fields marked as required and marked as infocollectors. When I try to edit the content I am forced to enter the required fields as wall although they are infocollectors. After submission I get the following error:
{
    "ErrorMessage": {
        "_media-type": "application\/vnd.ez.api.ErrorMessage+json",
        "errorCode": 400,
        "errorMessage": "Bad Request",
        "errorDescription": "Content fields did not validate",
        "errorDetails": {
            "fields": [
                {
                    "_fieldTypeId": 462,
                    "errors": [
                        {
                            "type": "empty",
                            "message": "Value for required field definition 'form_name' with language 'eng-GB' is empty"
                        }
                    ]
                },
                {
                    "_fieldTypeId": 463,
                    "errors": [
                        {
                            "type": "empty",
                            "message": "Value for required field definition 'form_vorname' with language 'eng-GB' is empty"
                        }
                    ]
                },
                {
                    "_fieldTypeId": 471,
                    "errors": [
                        {
                            "type": "empty",
                            "message": "Value for required field definition 'nachricht' with language 'eng-GB' is empty"
                        }
                    ]
                }
            ]
        },
        "trace": "#0 \/var\/www\/disk2\/hussl\/vendor\/ezsystems\/platform-ui-bundle\/Controller\/Rest\/ContentController.php(92): eZ\\Publish\\Core\\REST\\Server\\Controller\\Content->updateVersion('91', '8', Object(Symfony\\Component\\HttpFoundation\\Request))\n#1 [internal function]: EzSystems\\PlatformUIBundle\\Controller\\Rest\\ContentController->updateVersion('91', '8', Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 \/var\/www\/disk2\/hussl\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php(144): call_user_func_array(Array, Array)\n#3 \/var\/www\/disk2\/hussl\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 \/var\/www\/disk2\/hussl\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/DependencyInjection\/ContainerAwareHttpKernel.php(69): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 \/var\/www\/disk2\/hussl\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php(185): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 \/var\/www\/disk2\/hussl\/web\/app.php(70): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#7 {main}",
        "file": "\/var\/www\/disk2\/hussl\/vendor\/ezsystems\/ezpublish-kernel\/eZ\/Publish\/Core\/REST\/Server\/Controller\/Content.php",
        "line": 469
    }
}

I am using the following latest packages:

v1.3.0 (30.03.17 16:15, 78dfd)
ezsystems/content-on-the-fly-prototype
v0.1.11 (24.07.17 16:26, 14f95)
ezsystems/ez-support-tools
v0.1.2 (23.11.16 14:30, 0eb66)
ezsystems/ezplatform-design-engine
v1.0.1 (27.07.17 17:11, ac1c5)
ezsystems/ezplatform-http-cache
v0.1.1 (28.03.17 13:34, a107c)
ezsystems/ezplatform-multi-file-upload
v0.1.2 (12.06.17 10:20, a6c07)
ezsystems/ezplatform-solr-search-engine
v1.4.2 (16.08.17 17:18, a46cb)
ezsystems/ezpublish-kernel
v6.11.1 (23.08.17 21:06, 25008)
ezsystems/platform-ui-assets-bundle
v3.3.0 (08.08.17 11:45, d4b96)
ezsystems/platform-ui-bundle
v1.11.0 (09.08.17 12:42, aa4ec)
ezsystems/repository-forms
v1.9.0.1 (28.08.17 22:37, 45f31)

**Comment by MarioBlazek** [comment]
Thanks for reporting the issue, I will resolve it asap.

**Comment by punknroll** [comment]
Hi,
somebody on the slack channel just reported the same issue. This is probably a bug in ezplatform. I will investigate.

**Comment by punknroll** [comment]
This is bug in ezplatform so I close this issue.

**Comment by MarioBlazek** [comment]
@punknroll thanks for info. Please if you find more info paste it here.

**Comment by punknroll** [comment]
This issue is reported here https://jira.ez.no/browse/EZP-27863
