### ISSUE TITLE
Is it work for non-enterprise version?

### ISSUE THREAD

**Issue by david-adam** [netgen/NetgenInformationCollectionBundle#31]
I am playing the eZplatform in my spare time to see how it works. I realize that there is no built-in Informaiton Colletion field, and found your bundle. However, I have followed the instructions to install it and can't get it to work so that I can mark a field type as information collector.

I have tried many times and different versions of ezplatform, but not the enterprise version. I have see any errors from composer. I installed a new fresh clean installation.

    Registered the bundle
    updated the routing config
    update the system config for actions
    cleared the cache

But I can't see any changes in the administrative interface. Am I  missing something?

Looking forward to hearing from you.

**Comment by MarioBlazek** [comment]
@david-adam please check your mailbox :)

**Comment by SteffiKn** [comment]
@MarioBlazek Why don't you comment your answer here? That could help more people I guess.
