### ISSUE TITLE
Mail is not sent, collected info doesn't show up

### ISSUE THREAD

**Issue by SteffiKn** [netgen/NetgenInformationCollectionBundle#33]
eZPlatform Version 2.4

I followed the documentation, the form is displayed and I can send it. Seemingly successful, at least I get the success message.
I use a seperate template for email:
`email:
          templates:
            default: "email/form_collect_data.html.twig"`

which only contains the email block and a sample text:
`{% block email %}
    New mail received through example.de website!
{% endblock %}`

In the app/config/ezplatform.yml file I configured to execute both 'email' and 'database' as default actions.
The default_variables all contain valid values of course.

Maybe some configurations are missing? Unfortunately I couldn't find any further configs for sending mails or saving the collected data of the form fields.

I expected that in the admin panel a new tab is showing up as soon as there is data collected the first time.

Any Ideas on what is wrong or missing?

**Comment by MarioBlazek** [comment]
@SteffiKn can you see collected information in admin? Do you see the email in Symfony Profiler toolbar?

**Comment by SteffiKn** [comment]
@MarioBlazek 
No, there is nowhere collected information in the admin gui visible. Where should it be? 
The email is not sent, but I found the database entries for the form values in the table 'ezinfocollection_attribute'.

**Comment by SteffiKn** [comment]
@MarioBlazek It's version 1.5

**Comment by SteffiKn** [comment]
@MarioBlazek Any news?

**Comment by MarioBlazek** [comment]
@SteffiKn are you a member on ezcommunity slack? If so can we continue the discussion there?

**Comment by SteffiKn** [comment]
@MarioBlazek Yes, I am
