### ISSUE TITLE
Infocollection admin interface is incompatible with MySQL 5.7+

### ISSUE THREAD

**Issue by darinda** [netgen/NetgenInformationCollectionBundle#34]
When trying to access the infocollection admin interface on a server with MySQL 5.7+ installed there will be a fatal error:

`An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT eco.id AS content_id, eco.name, ecot.main_node_id, ecc.serialized_name_list, ecc.identifier AS class_identifier FROM `ezcontentobject` eco LEFT JOIN `ezcontentobject_tree` ecot ON `eco`.`id` = `ecot`.`contentobject_id` INNER JOIN `ezcontentclass` ecc ON `eco`.`contentclass_id` = `ecc`.`id` WHERE (ecc.version = 0) AND (eco.id IN (637, 1414, 1563)) GROUP BY `ecot`.`main_node_id` LIMIT 10'`

This is caused by MySQL's `only_full_group_by` mode being turned on [as explained in this issue on Stackoverflow](https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc).

It can be fixed by [aggregating the selected columns in the corresponding controller](https://github.com/netgen/NetgenInformationCollectionBundle/blob/1.x/bundle/Core/Persistence/Gateway/DoctrineDatabase.php#L94) instead of only `select`ing the values which would produce unpredictable results.

Using the `max` aggregation function on all `select`ed fields should be ok in this case because the column's values will always be the same for all rows matched by the group by clause.

**Comment by MarioBlazek** [comment]
Fixed, thanks for reporting @darinda.
