### ISSUE TITLE
Error on admin route when creator of infocollection has been deleted

### ISSUE THREAD

**Issue by darinda** [netgen/NetgenInformationCollectionBundle#45]
When accessing the collected info backend (/admin/netgen/informationcollection/collection-list/[contentId]) for a content where an infocollection exists that has been created by a user that no longer exists, there will be an error.

Currently this is can only be fixed by manually updating the `creator_id` of the infocollection (directly in the database) to an existing user's id.

**Comment by MarioBlazek** [comment]
@darinda sorry I've somehow missed this issue report will fix ASAP.
