### ISSUE TITLE
Hyphens in parameter placeholder names break the query on Mysql 8

### ISSUE THREAD

**Issue by hknezevic** [netgen/NetgenInformationCollectionBundle#75]
For example:
```
public function findByCollectionId($collectionId)
{
    $qb = $this->createQueryBuilder('eica');

    return $qb->select('eica')
        ->where('eica.informationCollectionId = :collection-id')
        ->setParameter('collection-id', $collectionId)
        ->getQuery()
        ->getResult();
}
```

throws a following error:

`[Semantical Error] line 0, col 146 near 'id': Error: 'id' is not defined.`

This was first noticed in setup using Mysql 8 with default configuration, PHP, Symfony and Doctrine versions match some of the previous projects where the issue was not occuring. The only difference is Mysql 8 being used instead of Mysql 5.7

Course of action: replace all placeholder names  in all of the queries with camel case format

Error present in both 1.x and master/2.x versions

**Comment by leohajder** [comment]
Issue fixed in https://github.com/netgen/NetgenInformationCollectionBundle/pull/74/commits/3bed352d702cb57cac89af564203a015a72a52cb
